### ISSUE TITLE
#enhancement  Tracking the sender

### ISSUE THREAD

**Issue by DrEinyel** [bakatrouble/sys-screenuploader#4]
#enhancement  

![image](https://user-images.githubusercontent.com/54357529/79182171-2a0d1900-7ddc-11ea-8a80-c905f9919c0e.png)

It would be REALLY usefull if there was a way to add a tittle or something to the upload containing any information from the sender, for example the Profiles names on the Switch or something. 

This could be something optional and activable when creating a new Destination. For example, 

It would be amazing to have this, so people in common servers (in my case, Animal Crossing Server) could automatically upload their screenshots while playing.

Till there's no way to track who sent the photo, this amazing tool won't be compatible with this kind of uses.

I would like to know if this is possible in the future.

Still it's an amazing tool and I'm asking the members of my Server to start using it individually and then foward the screenshot.

**Comment by bakatrouble** [comment]
Closed by https://github.com/bakatrouble/sys-screenuploader/commit/1b3b5b50fcce5bdcf9784d2785cd152d7867e4f1
